// Single source of truth mapping a route path to its i18n label key.
// Used by the sidebar favorites/recent resolution, breadcrumbs, and
// recent-page visit logging. Keep in sync with the sidebar navGroups.
export const navPathLabels: Record<string, string> = {
  '/': 'nav.dashboard',
  '/patients': 'nav.patients',
  '/appointments': 'nav.appointments',
  '/emr': 'nav.emr',
  '/queue': 'nav.queue',
  '/referrals': 'nav.referrals',
  '/nursing': 'nav.nursing',
  '/home-visits': 'nav.homeVisits',
  '/telemedicine': 'nav.telemedicine',
  '/laboratory': 'nav.laboratory',
  '/radiology': 'nav.radiology',
  '/pharmacy': 'nav.pharmacy',
  '/billing': 'nav.billing',
  '/insurance': 'nav.insurance',
  '/insurance-claims': 'nav.insuranceClaims',
  '/expenses': 'nav.expenseTracking',
  '/eta-invoicing': 'nav.etaInvoicing',
  '/inventory': 'nav.inventory',
  '/hr': 'nav.hr',
  '/dms': 'nav.dms',
  '/workflow': 'nav.workflow',
  '/forms': 'nav.forms',
  '/compliance': 'nav.compliance',
  '/automation': 'nav.automation',
  '/bi': 'nav.bi',
  '/reports': 'nav.reports',
  '/compliance-reports': 'nav.complianceReports',
  '/advanced-reporting': 'nav.advancedReporting',
  '/analytics-dashboard': 'nav.analyticsDashboard',
  '/ai-hub': 'nav.aiHub',
  '/clinical-ai': 'nav.clinicalAI',
  '/predictive-analytics': 'nav.predictiveAnalytics',
  '/smart-scheduling': 'nav.smartScheduling',
  '/notifications': 'nav.notifications',
  '/communications': 'nav.communications',
  '/whatsapp': 'nav.whatsapp',
  '/whatsapp-templates': 'nav.whatsappTemplates',
  '/voice-calls': 'nav.voiceCalls',
  '/chat': 'nav.chat',
  '/patient-messages': 'nav.patientMessages',
  '/patient-portal': 'nav.patientPortal',
  '/online-booking': 'nav.onlineBooking',
  '/patient-app': 'nav.patientApp',
  '/patient-self-service': 'nav.patientSelfService',
  '/post-visit-survey': 'nav.postVisitSurvey',
  '/kiosk': 'nav.kiosk',
  '/queue-display': 'nav.queueDisplay',
  '/saas-billing': 'nav.saasBilling',
  '/white-label': 'nav.whiteLabel',
  '/integrations': 'nav.integrations',
  '/dr-backup': 'nav.drBackup',
  '/regions': 'nav.regions',
  '/branches': 'nav.multiBranch',
  '/barcodes': 'nav.barcodes',
  '/data-warehouse': 'nav.dataWarehouse',
  '/api-keys': 'nav.apiKeys',
  '/developer-portal': 'nav.developerPortal',
  '/data-export': 'nav.dataExport',
  '/bulk-import': 'nav.bulkImport',
  '/data-import-advanced': 'nav.dataImport',
  '/settings': 'nav.settings',
  '/admin': 'nav.admin',
  '/security': 'nav.security',
  '/audit-logs': 'nav.auditLogs',
  '/audit-logs-advanced': 'nav.auditLogsAdvanced',
  '/notification-templates': 'nav.notificationTemplates',
  '/notification-logs': 'nav.notificationLogs',
  '/sessions': 'nav.sessions',
  '/system-monitor': 'nav.systemMonitor',
  '/print-templates': 'nav.printTemplates',
  '/user-preferences': 'nav.userPreferences',
  '/departments': 'nav.departments',
  '/emergency-access': 'nav.emergencyAccess',
};

export function resolveNavLabelKey(pathname: string): string | undefined {
  if (navPathLabels[pathname]) return navPathLabels[pathname];
  const segments = pathname.split('/').filter(Boolean);
  if (segments.length > 1) return navPathLabels[`/${segments[0]}`];
  return undefined;
}
