import { getEnv } from '@healthcare/shared/config';
import { db } from '../core/database.js';
import { logAudit } from './audit.js';

const CURRENCIES: Record<string, { symbol: string; rate: number }> = {
  SAR: { symbol: 'ر.س', rate: 1 },
  USD: { symbol: '$', rate: 3.75 },
  EUR: { symbol: '€', rate: 4.05 },
  AED: { symbol: 'د.إ', rate: 1.02 },
  EGP: { symbol: 'ج.م', rate: 0.12 },
};

export function getCurrencyInfo(code: string) {
  return CURRENCIES[code] || CURRENCIES.EGP; // Default to EGP for Egypt market
}

export function convertCurrency(amount: number, from: string, to: string): number {
  const fromInfo = getCurrencyInfo(from);
  const toInfo = getCurrencyInfo(to);
  const sarAmount = amount / fromInfo.rate;
  return Math.round(sarAmount * toInfo.rate * 100) / 100;
}

interface PaymentResult {
  success: boolean;
  paymentId?: string;
  redirectUrl?: string;
  reference?: string;
  error?: string;
}

// Generate Fawry payment reference
export function generateFawryPayment(invoiceId: string, amount: number, customerPhone: string, customerName: string, customerEmail: string): PaymentResult {
  const env = getEnv();
  if (!env.FAWRY_MERCHANT_CODE) {
    return { success: false, error: 'Fawry is not configured. Add FAWRY_MERCHANT_CODE to environment.' };
  }

  const merchantCode = env.FAWRY_MERCHANT_CODE;
  const merchantRef = `INV-${invoiceId.substring(0, 8)}-${Date.now()}`;
  const securityKey = env.FAWRY_SECURITY_KEY || '';

  // In production, this would call Fawry API
  // For now, generate the payment reference that would be sent to Fawry
  const paymentRef = `FR-${Date.now()}-${Math.random().toString(36).substring(2, 8).toUpperCase()}`;

  return {
    success: true,
    paymentId: paymentRef,
    reference: merchantRef,
    redirectUrl: `https://atfawry.com/ECommercePlugin/pay?merchantCode=${merchantCode}&merchantRefNumber=${merchantRef}&amount=${amount}&currencyCode=EGP&description=Invoice%20Payment&customerEmail=${encodeURIComponent(customerEmail)}&customerPhone=${encodeURIComponent(customerPhone)}`,
  };
}

// Generate InstaPay payment link (Egypt's instant payment network)
export function generateInstaPayPayment(amount: number, merchantWallet: string): PaymentResult {
  const env = getEnv();
  if (!env.INSTAPAY_WALLET) {
    return { success: false, error: 'InstaPay is not configured. Add INSTAPAY_WALLET to environment.' };
  }

  // InstaPay uses QR codes generated by the merchant's bank
  // The wallet number is the merchant's registered InstaPay wallet
  return {
    success: true,
    reference: `IP-${Date.now()}`,
    redirectUrl: `instapay://send?wallet=${env.INSTAPAY_WALLET}&amount=${amount}`,
    paymentId: `IPAY-${Date.now()}-${Math.random().toString(36).substring(2, 6).toUpperCase()}`,
  };
}

// Generate Egyptian E-Invoicing QR Code data (ETA format)
export function generateEtaQrCode( sellerName: string, taxRegistrationNumber: string, timestamp: string, total: number, taxTotal: number ): string {
  // ETA QR code format (TLV - Tag Length Value)
  // Tag 1: Seller Name
  // Tag 2: VAT Registration Number
  // Tag 3: Time Stamp
  // Tag 4: Invoice Total
  // Tag 5: Total VAT
  const tlv = {
    1: sellerName,
    2: taxRegistrationNumber,
    3: timestamp,
    4: total.toFixed(2),
    5: taxTotal.toFixed(2),
  };
  // Return base64-encoded JSON (simplified — in production, use proper TLV encoding)
  return Buffer.from(JSON.stringify(tlv)).toString('base64');
}

// Stripe payment
export async function createStripePayment(invoiceId: string, amount: number, currency: string, tenantId: string): Promise<PaymentResult> {
  const env = getEnv();
  if (!env.STRIPE_SECRET_KEY) {
    return { success: false, error: 'Stripe is not configured.' };
  }
  try {
    const stripe = require('stripe')(env.STRIPE_SECRET_KEY);
    const invoice = await db('invoices').where({ id: invoiceId, tenant_id: tenantId }).first();
    if (!invoice) return { success: false, error: 'Invoice not found' };
    const patient = await db('patients').where({ id: invoice.patient_id }).first();
    const tenant = await db('tenants').where({ id: tenantId }).first();
    const session = await stripe.checkout.sessions.create({
      payment_method_types: ['card'],
      customer_email: patient?.email || undefined,
      line_items: [{
        price_data: {
          currency: currency.toLowerCase(),
          product_data: { name: `Invoice ${invoice.invoice_number} — ${tenant?.name || 'Healthcare'}` },
          unit_amount: Math.round(amount * 100),
        },
        quantity: 1,
      }],
      mode: 'payment',
      metadata: { invoiceId, tenantId },
      success_url: `${env.APP_URL}/billing?payment=success&invoice=${invoiceId}`,
      cancel_url: `${env.APP_URL}/billing?payment=cancelled&invoice=${invoiceId}`,
    });
    await db('payment_transactions').insert({ tenant_id: tenantId, invoice_id: invoiceId, amount, method: 'online', reference: session.id, notes: 'Stripe checkout', status: 'pending' });
    await logAudit({ tenantId, action: 'payment.stripe.create', entityType: 'invoice', entityId: invoiceId, metadata: { amount, currency } });
    return { success: true, paymentId: session.id, redirectUrl: session.url };
  } catch (err: any) {
    return { success: false, error: err.message };
  }
}

// Confirm Stripe payment (webhook)
export async function confirmStripePayment(sessionId: string): Promise<boolean> {
  const env = getEnv();
  if (!env.STRIPE_SECRET_KEY) return false;
  try {
    const stripe = require('stripe')(env.STRIPE_SECRET_KEY);
    const session = await stripe.checkout.sessions.retrieve(sessionId);
    if (session.payment_status !== 'paid') return false;
    const { invoiceId, tenantId } = session.metadata;
    const amountPaid = session.amount_total / 100;
    const invoice = await db('invoices').where({ id: invoiceId }).first();
    if (!invoice) return false;
    const newPaid = Number(invoice.paid) + amountPaid;
    const newDue = Number(invoice.total) - newPaid;
    await db('invoices').where({ id: invoiceId }).update({ paid: newPaid, due: Math.max(0, newDue), status: newDue <= 0 ? 'paid' : 'partial', payment_method: 'online', paid_at: new Date() });
    await db('payment_transactions').where({ reference: sessionId }).update({ status: 'completed' });
    await logAudit({ tenantId, action: 'payment.stripe.confirm', entityType: 'invoice', entityId: invoiceId });
    return true;
  } catch (err: any) {
    return false;
  }
}

export function generatePaymentLink(invoiceId: string, tenantSlug: string): string {
  const env = getEnv();
  return `${env.APP_URL}/pay/${tenantSlug}/${invoiceId}`;
}
